In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import *
from sklearn.metrics import *
import math

<h3>Read Data</h3>

In [2]:
df=pd.read_csv("magic04.data",header=None)

In [3]:
df.head(1)

,0,1,2,3,4,5,6,7,8,9,10
0,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.011,-8.2027,40.092,81.8828,g

In [4]:
# classes replaced to be 0 and 1 
df[10] = df[10].replace({'g': 0, 'h': 1})
df.head()

/tmp/ipykernel_20841/538172084.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[10] = df[10].replace({'g': 0, 'h': 1})

,0,1,2,3,4,5,6,7,8,9,10
0,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.0110,-8.2027,40.0920,81.8828,0
1,31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.2610,0
2,162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.7880,0
3,23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.7370,0
4,75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.4620,0

In [5]:
# balancing data
g=df[0:12332]
g=g.sample(n=len(g),random_state=42)
h=df[12332:len(df)+1]
g=g[0:6688]
df[0:6688]=g
df[6688:2*6688]=h

In [6]:
y=df.iloc[0:2*6688,10]
x=df.iloc[0:2*6688,0:10]

Splitting the data

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3,random_state=42,shuffle=True)
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, test_size = 0.5,random_state=42,shuffle=True)
#x_train_2,x_train_3,x_train_4=x_train.copy()

In [8]:
scaler = StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_val=scaler.transform(x_val)

# k=1

Training the model

In [9]:
k_classifier=KNeighborsClassifier(n_neighbors=1,metric='euclidean')
k_classifier.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=1)

Testing using the validation set

In [10]:
# predict values of validation set
y_preds_val=k_classifier.predict(x_val)

# confusion matrix
cm_val=confusion_matrix(y_val, y_preds_val)

# f1 score
f1_val=f1_score(y_val, y_preds_val)

# accuracy
acc_score_val=accuracy_score(y_val, y_preds_val)


scores={k_classifier:acc_score_val}

In [11]:
 #tp fp
#fn tn
#f1=2*(pr*recall)/(pr+recall)
#acc=(tp+tn)/(tp+tn+fp+fn)

Evaluating the model

# k=3

In [12]:
k_classifier_3=KNeighborsClassifier(n_neighbors=3,metric='euclidean')
k_classifier_3.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [13]:
# predict values of validation set
y_preds_val=k_classifier_3.predict(x_val)

# confusion matrix
cm_val=confusion_matrix(y_val, y_preds_val)

# f1 score
f1_val=f1_score(y_val, y_preds_val)

# accuracy
acc_score_val=accuracy_score(y_val, y_preds_val)


scores[k_classifier_3]=acc_score_val

# K=9

In [14]:
k_classifier_9=KNeighborsClassifier(n_neighbors=9,metric='euclidean')
k_classifier_9.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=9)

In [15]:
# predict values of validation set
y_preds_val=k_classifier_9.predict(x_val)

# confusion matrix
cm_val=confusion_matrix(y_val, y_preds_val)

# f1 score
f1_val=f1_score(y_val, y_preds_val)

# accuracy
acc_score_val=accuracy_score(y_val, y_preds_val)


scores[k_classifier_9]=acc_score_val

# k = root(n)

In [16]:
n=len(y_train)+len(y_test)+len(y_val)
best_k=math.floor(math.sqrt(n))

In [17]:
k_classifier_k=KNeighborsClassifier(n_neighbors=best_k,metric='euclidean')
k_classifier_k.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=115)

In [18]:
# predict values of validation set
y_preds_val=k_classifier_k.predict(x_val)

# confusion matrix
cm_val=confusion_matrix(y_val, y_preds_val)

# f1 score
f1_val=f1_score(y_val, y_preds_val)

# accuracy
acc_score_val=accuracy_score(y_val, y_preds_val)


scores[k_classifier_k]=acc_score_val

In [19]:
scores

{KNeighborsClassifier(metric='euclidean', n_neighbors=1): 0.7936191425722832,
 KNeighborsClassifier(metric='euclidean', n_neighbors=3): 0.8060817547357926,
 KNeighborsClassifier(metric='euclidean', n_neighbors=9): 0.8190428713858424,
 KNeighborsClassifier(metric='euclidean', n_neighbors=115): 0.7991026919242273}

In [26]:
# find max score to train its test set
best_model = max(scores, key=scores.get)
print(best_model)

KNeighborsClassifier(metric='euclidean', n_neighbors=9)

Testing the best model

In [21]:
y_preds=best_model.predict(x_test)

acc=accuracy_score(y_preds,y_test)
f1=f1_score(y_preds,y_test)
cm=confusion_matrix(y_preds,y_test)

In [22]:
print(f"Accuracy score : {acc}")
print(f"F1 score {f1}")
print(f"Confusion matrix {cm}")

Accuracy score : 0.8116591928251121
F1 score 0.7954545454545454
Confusion matrix [[894 262]
 [116 735]]

=====================================================================================================================================================================

<h3>KNN models</h3>

<h4>Best k is picked according to the accuracy because accuracy is the most effective metric for determining the optimal value of kk in a balanced dataset</h4>

4 values of k were used:<br><br>
k=1<br>
k=3<br>
k=9<br>
k=root(n)<br><br>




<h4>Best K value</h4>
k = 9