In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import *
from sklearn.metrics import *
import math

In [2]:
df=pd.read_csv("magic04.data",header=None)

In [3]:
df.head(1)

,0,1,2,3,4,5,6,7,8,9,10
0,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.011,-8.2027,40.092,81.8828,g

In [4]:
df[10] = df[10].replace({'g': 0, 'h': 1})
df.head()

,0,1,2,3,4,5,6,7,8,9,10
0,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.0110,-8.2027,40.0920,81.8828,0
1,31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.2610,0
2,162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.7880,0
3,23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.7370,0
4,75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.4620,0

In [5]:
g=df[0:12332]
g=g.sample(n=len(g))
h=df[12332:len(df)+1]
g=g[0:6688]
df[0:6688]=g
df[6688:2*6688]=h

In [6]:
y=df.iloc[0:2*6688,10]
x=df.iloc[0:2*6688,0:10]

Splitting the data

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3,random_state=42,shuffle=True)
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, test_size = 0.5,random_state=42,shuffle=True)

In [8]:
scaler = StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_val=scaler.transform(x_val)

In [9]:
# KNN at k=1

Training the model

In [10]:
k_classifier=KNeighborsClassifier(n_neighbors=1,metric='euclidean')
k_classifier.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=1)

Testing using the validation set

In [11]:
y_preds_val=k_classifier.predict(x_val)
cm_val=confusion_matrix(y_val, y_preds_val)
f1_val=f1_score(y_val, y_preds_val)
acc_score_val=accuracy_score(y_val, y_preds_val)

Testing using the test dataset

In [12]:
y_preds=k_classifier.predict(x_test)
cm=confusion_matrix(y_test, y_preds)
f1=f1_score(y_test, y_preds)
acc_score=accuracy_score(y_test, y_preds)

In [13]:
 #tp fp
#fn tn
#f1=2*(pr*recall)/(pr+recall)
#acc=(tp+tn)/(tp+tn+fp+fn)

Evaluating the model

In [14]:
print(acc_score)
print(f1)
print(cm)

0.7892376681614349
0.7802597402597402
[[833 177]
 [246 751]]

KNN at k=3

In [15]:
k_classifier_3=KNeighborsClassifier(n_neighbors=3,metric='euclidean')
k_classifier_3.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [16]:
y_preds_val=k_classifier_3.predict(x_val)
cm_val=confusion_matrix(y_val, y_preds_val)
f1_val=f1_score(y_val, y_preds_val)
acc_score_val=accuracy_score(y_val, y_preds_val)

In [17]:
y_preds=k_classifier_3.predict(x_test)
cm=confusion_matrix(y_test, y_preds)
f1=f1_score(y_test, y_preds)
acc_score=accuracy_score(y_test, y_preds)

In [18]:
print(acc_score)
print(f1)
print(cm)

0.7952167414050823
0.7826546800634584
[[856 154]
 [257 740]]

K=9

In [19]:
k_classifier_9=KNeighborsClassifier(n_neighbors=9,metric='euclidean')
k_classifier_9.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=9)

In [20]:
y_preds_val=k_classifier_9.predict(x_val)
cm_val=confusion_matrix(y_val, y_preds_val)
f1_val=f1_score(y_val, y_preds_val)
acc_score_val=accuracy_score(y_val, y_preds_val)

In [21]:
y_preds=k_classifier_9.predict(x_test)
cm=confusion_matrix(y_test, y_preds)
f1=f1_score(y_test, y_preds)
acc_score=accuracy_score(y_test, y_preds)

In [22]:
print(acc_score)
print(f1)
print(cm)

0.8031888390632785
0.7870619946091645
[[882 128]
 [267 730]]

In [23]:
n=len(y_train)+len(y_test)+len(y_val)
best_k=math.floor(math.sqrt(n))

In [24]:
k_classifier_k=KNeighborsClassifier(n_neighbors=best_k,metric='euclidean')
k_classifier_k.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=115)

In [25]:
y_preds_val=k_classifier_k.predict(x_val)
cm_val=confusion_matrix(y_val, y_preds_val)
f1_val=f1_score(y_val, y_preds_val)
acc_score_val=accuracy_score(y_val, y_preds_val)

In [26]:
y_preds=k_classifier_k.predict(x_test)
cm=confusion_matrix(y_test, y_preds)
f1=f1_score(y_test, y_preds)
acc_score=accuracy_score(y_test, y_preds)

In [27]:
print(acc_score)
print(f1)
print(cm)

0.7952167414050823
0.7752870420995078
[[887 123]
 [288 709]]